- hosts: all
  vars_files: 
    - vars.yml
    - vault.yml

  tasks:
  - name: Python 2.7
    apt: 
      name: python=2.7*
      state: present
    become: yes

  - name: Pip
    apt:
      name: python-pip
    become: yes

  - name: Pip Install Docker API
    pip: 
      name: docker

  - name: Make image dir
    file:
      path: images
      state: directory
    
  - name: Build Master Docker Image
    docker_image:
      name: "{{ master.image_name }}"
      build:
        path: .
      source: build
      state: present
      force_source: true

  - name: Configure Master Docker Container {{ master.image_name }}
    docker_container:
      name: "{{ master.container_name }}"
      image: "{{ master.image_name }}"
      state: present
      detach: true
      ports:
      - "8080:8080"
      volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    register: master_container

  - name: Start Master Docker Container {{ master.container_name }}
    docker_container:
      name: "{{ master.container_name }}"
      state: started

  - name: Change docker.sock owner to jenkins
    command: docker exec --user=root "{{ master.container_name }}" \
      chown jenkins:jenkins /var/run/docker.sock
  
  - name: Build Agent Docker Images
    docker_image:
      name: "{{ item.image_name }}"
      source: pull
    loop: "{{ clients }}"
