- hosts: all
  vars_files: vars.yml

  tasks:
  - name: Python 2.7
    apt: 
      name: python=2.7*
      state: present
    become: yes

  - name: Pip
    apt:
      name: python-pip
    become: yes

  - name: Pip Install Docker API
    pip: 
      name: docker

  - name: Configure Master Docker Container {{ master.image_name }}
    docker_container:
      name: "{{ master.container_name }}"
      image: "{{ master.image_name }}"
      state: present
      ports:
      - "8080:8080"
      volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:{{ lookup('env','DOCKER_HOST') }}"
    register: master_container

  - name: Start Master Docker Container {{ master.container_name }}
    docker_container:
      name: "{{ master.container_name }}"
      state: started

  - name: Build Agent Docker Images
    docker_image:
      name: "{{ item.image_name }}"
      tag: "{{ item.tag }}"
      source: pull
    loop: "{{ clients }}"