- hosts: all
  vars_files: vars.yml

  tasks:
  - name: Python 2.7
    apt: 
      name: python=2.7*
      state: present
    become: yes

  - name: Pip
    apt:
      name: python-pip
    become: yes

  - name: Pip Install Docker API
    pip: 
      name: docker

  - name: Configure Docker Container {{ image_name }}
    docker_container:
      name: "{{ container_name }}"
      image: "{{ image_name }}"
      state: present
      ports:
      - "8080:8080"
      volumes:
      - "jenkins_home:/var/jenkins_home"
    register: master_container

  - name: Start Docker Container {{ container_name }}
    docker_container:
      name: "{{ container_name }}"
      state: started

