- hosts: all
  vars_files: vars.yml

  tasks:
  - name: Stop Docker Container {{ container_name }}
    docker_container:
      name: "{{ container_name }}"
      state: absent
      keep_volumes: yes

